---
- name: Fail loudly if backup credentials aren't set
  fail:
    msg: "Backup credential env vars not set — did you run 'source ~/homelab-env.sh'?"
  when: >
    inventory_hostname == groups['rke2_nodes'][0] and
    (lookup('env', 'BACKUP_CREDS_JSON') == "")

- name: Create backup chain credentials secret in rocinante namespace
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: backup-chain-credentials
        namespace: rocinante
      type: Opaque
      stringData: "{{ lookup('env', 'BACKUP_CREDS_JSON') | from_json }}"
  when: inventory_hostname == groups['rke2_nodes'][0]