client_secret: ENC[AES256_GCM,data:5F1wUfYltuawguyqPCgsv2aKLvTKPHc+BOq3m281p6pj9RTrvDXbyQ==,iv:BtvOpBNZT7j3laIa6crgjUaZRSzijqNgOXtuF7YjBrY=,tag:T4c7e85kDHJMRWkSjtXF8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZ0JVdms5Q3BudTlOUUIr
            QlhrMDErTnMwVFNzTS80WktiL0N1dkhnTVFvCjJ2VFZPZCtiNkI1WmowUzJ2ZFZS
            RFo4Q0dEUnFOK08zOGR3UXMzMjFxbzQKLS0tIGFPb0VSM1dYVnZRRTZTTUExemNX
            dHFwU056Y2NlS3o3Z1pDZm16UXdMMVEKip9xZY1U2x4vZOu8UL4gtcakO4Q11x9x
            kovJIeNDdhRwpmiJ660r8712JJLbx7frtC6MEfndDjtzwtz1annNRw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejlnhgwfnj7p5gxhvp8w0w52fg5n9k57xxzja2xqyneyu42ludyse4lfa6
    lastmodified: "2026-08-14T12:35:31Z"
    mac: ENC[AES256_GCM,data:CgP905bzV34LWcNhnknYH6KBqV8UUy6QG3ccH2Z75ar1Jl7BgwyjQf0suL3iOevTXHHLVaqubPcTYzFB18GSZGi3GHDfbh49l7oOjCGVmmZv++W3tcg04Tbt8jQg8zf0OE+Nts7LzmqluKl3UAf+CX9DwhvIp109EJk+B+5MNlw=,iv:bFMskU1wXkEBFO3FOGsMzsJbkJXWr3Cxj4gnJigJvQ8=,tag:qg+bbDjcvOikg64RPKKZ1Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
