b2_application_key_id: ENC[AES256_GCM,data:cHh+xmr+n/7IvmgV,iv:2NRehGYhOYXJMRdWPs2ZbY1xZY5/ZMMWffGfLmZprz4=,tag:0rhqBFDBZGxwEsTxwIXjnw==,type:str]
b2_application_key: ENC[AES256_GCM,data:FKPkX+4LEpllrpxS7ybBEWv4OtPVWQm6++JgxiLCSVfIMSRQftXHNI8a,iv:NfXgkD5esBp50pHTqbIDGzhoro4r11IDNsuVOX0hS5E=,tag:zcHVc0AQ4OGcfsMJUmfilw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTblB3Qmgxd0hpUUN6S1l6
            NUxYNERFWlJjVjc3NG90V1g2Z3hCbzNxZ21ZCngrcFpSWURHMGNnMlY3RUczS1R0
            dTRZdTF5UzFhMDNoVXRxajArLy9qeDQKLS0tIEJaTHJoM3RkUXVvT2FqSTJ6czYx
            U2pzZS9QZ1AzRlFMb2o3cHpwZnRaWlEKaQpamYh/V1qen08TQO+ryiKwTtu2encj
            cpNKQMCph0eCxR4YLs7D8Il5+NpkVItYHMcknd3r+0RHyjSglwlvzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejlnhgwfnj7p5gxhvp8w0w52fg5n9k57xxzja2xqyneyu42ludyse4lfa6
    lastmodified: "2026-09-03T09:51:18Z"
    mac: ENC[AES256_GCM,data:FMZUmjcdVmW17IKn7/mW+BsbC9SwoPVzqHMFM+BjB8g8yhvmhGdRO7ogLJFRNERggU+XMEgSiMdYF/sauthw9O59yIaBjlAE1ML6YIIuIwohUntaytoThO+yLHW+cEQ3eJSngiY84vyp+y4xg4LBdHmouG82MfRodWIr7qdwpmk=,iv:fYfWDv04PZcpGn0Yo5LhPgPj/Jq2m3x5u2hxfMgk9fw=,tag:TfMP0zxFgTrt0KhhrSD2Rg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
