ovh_s3_access_key: ENC[AES256_GCM,data:Oi/Bg2Po9/4hpOCfa8O8IoT7ZRRh3RaWIxMnDVk8fqo=,iv:tqDsVf/V0gUlY6/VqLdQxohOoFcI7tUCI7mW8etJaL8=,tag:lYUmGicI/y/sPqcgT8owtw==,type:str]
ovh_s3_secret_key: ENC[AES256_GCM,data:0T7pzHhmzHtk3zBBRHvGuQ3BJXYfb15HFhR08txZO/Y=,iv:OkQh6IeAt2vVBL0F0lTfqkGFnzxxv6NN2ypw0A7985w=,tag:VGwUvMqwJwth1Ggy3k2Waw==,type:str]
b2_key_id: ENC[AES256_GCM,data:ug/Vk4gjgw778oVyzR40ICQPUxuXtV+Dug==,iv:4XA1IPAbcMAzLf8fQX3NhKce1bpCwxMKwrp6FSN5Iw0=,tag:8LhId/LETYwbtQxim1W1Dg==,type:str]
b2_key_secret: ENC[AES256_GCM,data:yibgEo1Uy7bOjtPyJ5KTem0k+n4sOnQUlfudCql6xg==,iv:nX40xemGrJ+4qYqsMDLkKCiSWI00U4J7CD2l6/vDAxc=,tag:njPElmapX/KYWJPXRcPPow==,type:str]
azure_tenant_id: ENC[AES256_GCM,data:k2JGO/QNjhbJkqcuEcc9GOaKYgQxdnd2iGi6sQcvOZZvmDrG,iv:ou5Fs7H2SQQoVI3S+DkVvBjRz7ZRtKSy16yE4jhehAw=,tag:CTIFYbY1l4p4SqJHwl8AkA==,type:str]
azure_client_id: ENC[AES256_GCM,data:mb7GM3eL53l+SQE7RTvAJQAIUCB5h46o0P2aKBmdCulSKvui,iv:CCo1T21TGKztAFdV4Q8qxRv5RVdpBZ2wOfrkOOwdPxo=,tag:nqx7a84Tw98PVSGv0ERWiw==,type:str]
azure_client_secret: ENC[AES256_GCM,data:5AualbiXsbl5rWiFkxX7fP/tO1Gbuzw1bNFhW5Pfs7JsnRXf1e0j4w==,iv:lX+n51nh/Nc0FQoO+HLEVVmkXdoqft4qeNW+/iSYwD8=,tag:8HlX9QmWL5Gu/FfN+RomHA==,type:str]
bw_access_token: ENC[AES256_GCM,data:uVM06ecBrx6sRG32W8aqvNsr2DT8JSEeXxKjvPw0DAonXwrPeoL2fwcAfJ7hLEoHRuX57OcRufdg4q8/BvA087Ti6qUGaU0GgLa+T3Uau5VTy2PMfHnyxZsE8LL5Dw==,iv:vR6m4x+9Vw0dzg+Q3peuoKEcTG4osmRCzdIRO3vTWWQ=,tag:calN3HL83mv/lv03f2uAgQ==,type:str]
bw_project_id: ENC[AES256_GCM,data:1L1ghMY0anBTAexeBw/aM5uNd56bL80070ZX4nrJbeG16gHc,iv:GQvi3ozj9Mjh+ou61cEpvuqrJq/YZ/vvLIcO0rBIUSA=,tag:d9p8OhKVjmTM/zHIvwQFxg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdGg4bVZzdXpIYWJFeHVT
            bUJTNWl0V2g4WkVTbmN6THZZdXlMa0EvczNRCm9VS1JVZ0V4YVNYVzE5OWo1WCtS
            aFMxeHVjYnduYU9oQ3dZWFRMNm1LWjAKLS0tIEk3bUVMcnN2QloxVTdMTkgzMEM4
            U05tU2pZOUxqKy84eWFZa1d2aXhleVkKTfKH/U6P2JyfHMLfy/enoS9sqpPo+29L
            ADwa4gDCtjMEV65MBZp3x8N3xdH5oickZFOZfFSKxTtayYWS05tJsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejlnhgwfnj7p5gxhvp8w0w52fg5n9k57xxzja2xqyneyu42ludyse4lfa6
    lastmodified: "2026-09-04T07:02:00Z"
    mac: ENC[AES256_GCM,data:Yv7tts6tNQxabxA98pHHgyvzFNSbb2lxfLQs+tEBkrhgffZ7n0lnGwNR74yis2aTuHpYvNyaI1LxAXkM1VV4h5UsNJJd20V/Z3ceNp9GEJIiOK5c1nfDXIinX4rxiDUasRUvqUNMexDPTB2B2CV4+3Sbi2H2wbtapnp99M9KXJA=,iv:XqWPUuRdhgex51cDCg9U2Rc1AdzlCyQl1+owYy1ekPY=,tag:t5IUcvezjat36dC6jz5jOw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
