smtp_username: ENC[AES256_GCM,data:o3/24c20sJVNSOK1TF3EeWk=,iv:uPc5lffec0XQwKraForuQ8HEaQISQc8hiF7KPTCm5YE=,tag:2zmbJ97IHBjrL6SKa8nHAw==,type:str]
smtp_password: ENC[AES256_GCM,data:LizkTwFgGs1AOaCWBP/EybzTXJCb6DgPlypbUh947iA=,iv:v3YYZxcwXxogND74tN1QTHJtyV73Q0Qd9mZvmoVHhNQ=,tag:j5JTavyHuI6rreNryJAkJA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVkpxNUVtSHZxS0hMMDI4
            WUt0RXdIdDhFR1YyaXA0eHpOdFVHUEpzemtJClFPNjlXcjIwM3F6UXllUFN2R0Jv
            OU5kbEh2R2dkN0J4Rno2cHFOdFhkeHcKLS0tIHo0RTR4VTNlaVBLc2Q3QXp4NjBk
            UlRwWlVLVDZkeUIyT1paNWhhWTA4QjgKSFo3jjV9ACBAtLpvHThVpn/FgH2rt4OS
            iaLfnXWiZvNV6BTW2t5aLxy0xkTzde0mZ1/X0w2Z1RAjzhpoLWCQRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejlnhgwfnj7p5gxhvp8w0w52fg5n9k57xxzja2xqyneyu42ludyse4lfa6
    lastmodified: "2026-09-14T18:20:28Z"
    mac: ENC[AES256_GCM,data:SlLl8qD6QNDV7oLHlWP2ZpXLjvJywSaFe/V6IRgctDey2vYqjhCOE6vzOxdP5h39MRp5goXfeBgxIM85GLtRVZghhUBxRd86QiXvOfpV5lBpOhnWh/u3BFS9qGLGg+UqfVe7ArG9A+KAlJSp7S+ewg3TQ00XC3utScjdz2Djzpg=,iv:9dbxpjwQ0HvjWvOPn/gWYYWZdcqMUHqIqhI0ZZCMBAc=,tag:O+X7G8MCV1ZcENcdO4phRw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
