bw_access_token: ENC[AES256_GCM,data:hqOErEqKi8rhwb36S+/BbDjeUtSVCWiM1ytEzCxgnNTYl6o+5IWfWTVkyTosOchyv0Q7n/10knZUTU79BRmTPjbfNA6AeP6+mFfbJ/TJWAUgE16fuBDAlfvza6EFRA==,iv:5x0ojtFwEp65G1TRmpPLfSUBPbT4V/n3nT5ATKb0POA=,tag:fMQxfdosn5IpmaMQ54zlvQ==,type:str]
bw_organization_id: ENC[AES256_GCM,data:gi85D0HNDYxR6JVqWM/31QiX2FGBxleVi1VYVtB8vNHAmbZ4,iv:hquxZzmPISvudCCSShsM1a0OBfOlUKTIEQvK6uADEgc=,tag:lFCAhH/2OEIH1qBAxVHs2g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFamNXTFE1dEtRbzNNaEw0
            dkx4ZnNJMDdVN0dXcXQ5MC9Wd0dLdHdwUzFRCnl5Y01oLzVDQ2M0eWtGbnhuWVhO
            YzNDVGZ4dEloZ1lwNC80dXZOalpPQ2sKLS0tIFc4NkhIaU1nLzQwaW1nTGNYTGlq
            YmIwQWxZTGV5dmlvM3VwVENVcGk4SEkK2rH5F93BgxtB24arSUnzhFZeQEKMimbe
            dfpcNHeO8jgdtHn3ygNpVSxhqKXvQDZ5YwP9ky/aySzmx9y6vd8iTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejlnhgwfnj7p5gxhvp8w0w52fg5n9k57xxzja2xqyneyu42ludyse4lfa6
    lastmodified: "2026-09-03T14:00:24Z"
    mac: ENC[AES256_GCM,data:H2+sEGLGGzR4wL43GPDPC2t6um3BkgLfntHMFrZbHs1ItYE/P+GdJ3/yLD/sSwTArJSfSdi0/hEI/A2kxu9cCoAMFQ3XcL0dfA/gjufrKBDfecv+51jBCoR5Etimd0BWG6e/HKLZegVLrxFOFd8pYGadgHI4MweQ3MIQsQdc1jI=,iv:57mNmaOXIwycZV84cUOOHU/qaoIPUl/2dC8ZarzVnno=,tag:A8vddwjb2Nw1DJQIQ+Qcpw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
