cloudflare_api_token: ENC[AES256_GCM,data:bmwly6VOT/oIj6rIC6EyXeVBoCru9TvjlXES82bwoHwSCRNpEwscPda3QBKKf5x7FLUBp9A=,iv:vRHQyQianyHKtABdl+jAJt5V2O8S+gFDp/5rK45EkQM=,tag:JTjQN91awczR4Dt+7Z8vQw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VnFMRzlzb1d6RlhBMHBZ
            enY0cGZXY0NIbW5pekRqdEZ5d0x3Z25NT1JzCmpmZWorYmN3dWxPQVlMa3h2QktP
            Q0cvVStiUkVJVzlkUnlaMU13TEVIY28KLS0tIG85Q3hvNldLVjJVb2tkTU1Rcmtv
            aC9yQ2dzNUphaHNNTDZ5eE1mSDFhMVkK1QK6ggRIxKhTwvrev6IWISUfpF7qqztE
            pVLHqxpxXAx/4NbVMuEbcZPcm+cDZbeyTlRXIEhFuoIr3aMTEXB+Hg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejlnhgwfnj7p5gxhvp8w0w52fg5n9k57xxzja2xqyneyu42ludyse4lfa6
    lastmodified: "2026-08-12T11:50:37Z"
    mac: ENC[AES256_GCM,data:hhn8NHJd+1OJBMHg8FwQvWewMnUu+Jm7yMG+C57QhCIGgbkg+k71xaATsBUNZUlMduceXbHNquVXI0ffMPUHDFrrBcmzvS2BkGcs1vA+KNnCx/WCvBKTibDFOzE9rJOq4fwmaFmOtNDstE3FywYEtrgqVVS3xqXRxqjosystB04=,iv:o5hTCMZFV1R6opMvl2StNqZ1+i1CBJuECNbGT1vYkAM=,tag:TH3O4vSUlHRBvUvR7d929Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
