router_password: ENC[AES256_GCM,data:zq8RXug1HFfMxbOjsJuB+d89MmW1Vje4bLTxQ+iDS7Q=,iv:lM55UOpdMlDzHFzbJI7cdqPTUmVjjdlcKvcgBQnbqSs=,tag:hiP3ZzlhKkn2/j3ICU8IfQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5anlZelY2eEEzQklTbnE4
            RzVyeU0vbXhqbVZ2N2tNWmVxamo5U1FRUXdVCk5oZHF4WDZMWTM2S2Vvb3pqZXN3
            WWRRUGhmRXdxeWhYSkdYeVltbnZPQWMKLS0tIHIxYWNPakhrU252bnZuaU5jTnNP
            UWJNMGptQnQ5Tk10dklkSTc5Y3E5dmcKlMC4vPtc0oFVyPFj++syxTNgXbB6v7LP
            cPzyLADz2qZtLTBPEOQqo7PHad/Lz6zUJv3qnbZZD+XeQp5gq9GJiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejlnhgwfnj7p5gxhvp8w0w52fg5n9k57xxzja2xqyneyu42ludyse4lfa6
    lastmodified: "2026-08-26T12:23:22Z"
    mac: ENC[AES256_GCM,data:hpvQa28XChd3Bhod04qOfubt0cIWj4zgzfq8cBfCECUhQISJq/cngA/R2bHvVY9qQhO3HE77nKS05n1IFi9lr6I0b8/6ZQu//xpw0dn4a6UJrMhi9wBHmKiMBfdh6jkMU4/PmCDFDTo74matmowjfYLG0uwwLa/VzZPSUPDgmKY=,iv:oZlFFF6PEEwOfhEYFSYbERTDiUbMy7a/LIaFOtcIybA=,tag:s1M+D0IoR2qa4zmsHJ9HhA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
