ovh_application_key: ENC[AES256_GCM,data:JUjkVsRKH1uM5jcociG1iA==,iv:4BvTc2nhm59ujepakpRQe1kk0WbtXgx91seZw0DA0ks=,tag:u6sNbcTQSRP3tXgt+g1W6w==,type:str]
ovh_application_secret: ENC[AES256_GCM,data:NNCbebXEuWXUF3vcC3hq1OhEdFuxV1IOMUImUaw4RNY=,iv:tKNREmuebYNJgfE6ySOrulq1qWhsbrP519Tqjb0ozlQ=,tag:0SS/CQ33rS+lCBVugakc9Q==,type:str]
ovh_consumer_key: ENC[AES256_GCM,data:W0oxM/TAmsXh3OHYSd9/Wo9/hmDEHXTnPL+gz0/YRbk=,iv:X8slyetXlVQNu0eIZwwok5ayP5awO2cFSVVPbrKiWbc=,tag:atFdjPPTM0HOc2XQDQFSEQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacUpKN2I4YWU4ZHRHT2x5
            R1VxdlpWb2JzTGZoT3A5elFXSWNsYzcyQkdzCmNHZ3ROVkQwRlkybU5TekpVYnRO
            SEMzZHZoUVFkR1lETUUzeHR2MUJ0cEEKLS0tIEx6U0JRem9hMWc3eHNtcU5jUUdY
            RDFlOEpXUTBIMzlGTndnR2FxQ0NoN1kK5IJpaArdZezu2oLvCnGqfpF5ywVvwAPm
            WTJNLqPbc8HRvbwz23xBfem6nhJFVOpkUkWReJHW5VEbZJJ8vhuvGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejlnhgwfnj7p5gxhvp8w0w52fg5n9k57xxzja2xqyneyu42ludyse4lfa6
    lastmodified: "2026-09-03T09:25:53Z"
    mac: ENC[AES256_GCM,data:TzTIh+fRFysF6Fwl6UzCdRdAXBgwkGOsdnRw379ZBTCzesXdmTjDi4OQYErBxeWaXMKibvxmR9xRGWtw+WmT+XdSIfBvITmWfYjYSsoTdSK49ZnPYtrZZBhOdNBBXoX01LZyY1Xd+0yWPnfzqgXyY/xATkne6dIJ4WAyuKLh0oY=,iv:cHT3T/2w1OUZ+Zi0jvBxbjFbt1T0aBX2VF1fOs1heV4=,tag:bDeFUXOFow6yuUj/XJmxyg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
