cloudflare_api_token: ENC[AES256_GCM,data:pRFAp9GfiJrITZ1Vt1EuPLAI+pulVFH89LK/Z8tIWMMgUN8d/EdeAttueW3iUHLdAJAg37U=,iv:JUJSYcUhHPJBfZkC/+hTF4sWnJ+KTDZnHe5qmw9cw9I=,tag:kQUkVJZDcoyZ+/bJalhThw==,type:str]
cloudflare_zone_id: ENC[AES256_GCM,data:xkjUYJkL4wonPbXEMdEKsdtpyCl+KCeLxCBIAVU3CN4=,iv:4BjzoSVS1XuY2cN1L+i3iqaXVJwrW0FxhJSzaFHsOdM=,tag:18qs630WEPBLaQxwd7Aghg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKS2pPQlh4cjYrNDdFWGZa
            SkRQbHRTWkIzMEVpMmJjc0NGUTZRK3g1Skd3CjVSTU4rZThxUGlLcDdZL1NwbnZt
            WUtxMFQxdG1WNEJtWnFhUlhuREZxZGcKLS0tIG9WVnFWdk9QMFdiTk5qWG5HMVhL
            aDZDck9jVVZqZVRsVmU2cFZVay9vYmsKsttj29ccVJ4wUNOGdBsL7txRHfGR6rc2
            J58nMzs7Nfr/mXTavFSgykstG1H+6P2Od45eX06KUcREn8NJzzUkZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejlnhgwfnj7p5gxhvp8w0w52fg5n9k57xxzja2xqyneyu42ludyse4lfa6
    lastmodified: "2026-08-18T09:40:25Z"
    mac: ENC[AES256_GCM,data:5xlKK510kj/KVwrcsrTOm0z5tcXEz/536/KUidCfJjJqRJNB8u5LqUSjw3kkK8/zf4RXCwe+aT+m+Aem71U8V5zl+rNBd9GOLGxDkolmTuKJoNt4aSGhTZLYQTEcNjHLJGW61f0sJiF1bTlqiU5BEFD4cyCZQ4srLH7oMThQ7dw=,iv:tjidRhk8rYl43w6ulMBHVLt4RR0GVaJ3PyXLGn4hcKQ=,tag:4iCLMhrKohJF7qJpMVNBlQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
