client_secret: ENC[AES256_GCM,data:wih9pwAUmroF5HAytmQYpvLClVnx/bg4VZc19stFYMv8wq8pkxFzLw==,iv:jIk2Ufmm3aUOQVBQAIrvJaY0aXOF5X91ql3XtGoXm/U=,tag:eY6FA6Mvvo00/FljjRCS/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Y0s0ZEJRczE1NDB1enRi
            RFZORG03R2RyZDZROFFRS0xXTTlnNEEvV3hvCjIzeWJSc29UZFlJM0VpZWtxRnF4
            UzA4V1k3WGR6eXVCcE56TDhaaHFZTTAKLS0tIFRBcUdOb1MyQ0Z6dkpVY0lUMU53
            QWdWcmlLNUh6RTlRS21qcHhPZklhZ1kKhq/Av1A9jxrGYtduNHZwEbyHWuSvm77r
            zt6ByyAMBntM8ob0Zrv+CywLB12TedAQ9EuOHi4jHv/x2lJaFYFjAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejlnhgwfnj7p5gxhvp8w0w52fg5n9k57xxzja2xqyneyu42ludyse4lfa6
    lastmodified: "2026-08-19T14:04:49Z"
    mac: ENC[AES256_GCM,data:ZTbSI6Me3mz88femijSxzgHM/FarLlZXSEFtYR8YbHq5UdYMsN6e91o2ChilwBkuo32m28xm62f9uOxvBJEf57gnO/10cmSHZKK768OLLBLuuvelQmtJE6Ahw5o/wVoLrxdqlKg4vlzh3DbORNHZoWQwi+mNpJ1kGe8V7N6X1oQ=,iv:Goyd07ZI8qMUWdwXSgvvtILsbXFFblv69DRImH29+Fg=,tag:YJ2TlKkDMUeP6vftWLbe5g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
