cloudflare_api_token: ENC[AES256_GCM,data:BcqrUpV7nwKDyqR84ovPDyrfsA29/QZBkE5CZJRYvuoAJmwFpPKxxGSyEfPsgSEbHngWo40=,iv:J52CeB5Ed0y3ysOIQQ/KYCG8gBpP7cp/jD/JuFpvn9k=,tag:NOheHYAyBJsX2ZEnPyUdfw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcjhqRTkwOVhja1NNYW9U
            OU9wMlFPTXdScnhVL1hVWGh6UXlUdUJjRlQwCkJKeG9ncXVmUG9EeUtIUnBmVDR0
            dWM5dDU3ZXcva3Nsd0hja0JtallqY3cKLS0tIERmZXhEWktZTU4vbnRRSTBxMm1k
            QjdScnIybUFkRks3ZjNxTGZkWEI3TlEKueWvdf+ZN6R/fNvNDrCPv2aQquEzufp8
            /WmHc1A7oMEMZLPN9xsuzXIA7dcJem/y2Gclg5LSqiSlhppLLhskUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejlnhgwfnj7p5gxhvp8w0w52fg5n9k57xxzja2xqyneyu42ludyse4lfa6
    lastmodified: "2026-08-19T13:44:54Z"
    mac: ENC[AES256_GCM,data:eYmAtRh24oLWYLys/uC0mlnwfD9sI/fq47KG9wa8lbNnSTLfsFuEjeCQ4vZT4CTNpdRvmjZV/5wxPj+GW9OawiBZgTkfaQj80eR05fs3XzeqXw2QzBOabqo7aCiAxEEDCDm7+NDj6IYK780oTVmvbE9asTrilLunkZ2cBmWwTus=,iv:ieI+Pws3HHjx+FSdfjIBuuR8gvyYqHTvxFE7oSbvR1A=,tag:ajDMFrByJJQ4Pxx98QWFag==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
