client_id: ENC[AES256_GCM,data:3WKADihed6iWhOidjvAEF1nm3Sr0CUPWCPxCrzvesYG1PHkQ,iv:g6m99iak58In6LAN28uLcsu/h+3TmcPvnq0ev/65kns=,tag:vDg6k25JYyVfLx6ikl6nng==,type:str]
client_secret: ENC[AES256_GCM,data:UqlAECVTeofP7RQZZjSx1PQ/zl19hc22wr1fN3y4j6cWt4ZXz6HRmg==,iv:QSzeKgdVZmjkFh+yueaVOY/XR3flrn43D7f88OsbMl8=,tag:G3nlULU6wLhLePnrhA3McA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZmRCTHlLNjZIOWJnQklx
            ZU5MUE5aZmZRN2FwYWZ1bVFSczdmeFhaQjJZCmZNeGNNOG9ieW1TRGUvKyswNHRh
            dWsyK0lIS3U4VHVnVzJjcXhGMVcwY3MKLS0tICtpczJReEx5Ry9tZzVFcmFqMVd4
            RkZYQ3ZNN0l0U3MvTEpOZytTZEZNaFEKvVDhG5xe0wjdFC0Y8MsLjY0wQjR0iab1
            6e+i1SijzeB94Rl6aoezD+balTva11QyyaQvSlBF/80p8j/x1ggtEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejlnhgwfnj7p5gxhvp8w0w52fg5n9k57xxzja2xqyneyu42ludyse4lfa6
    lastmodified: "2026-08-24T14:27:12Z"
    mac: ENC[AES256_GCM,data:TRNj3XMasuplqFX0Y0PpB9WP9cd+DEFLatMAMMLSRDjqZ+QmCmnK+0WmCXSxHkuua3NemhGmmAZqqRboCqWpHvhBwopkzUr7taxadHB6q5T+W68IHnn7thLMNx73HQeUvC97kyNNxfZFxoI4ga14mZgsR4X8LWsz8e9kGqAIt9U=,iv:+tNx4rBqRQJDS6kbpMDpoN5NP5jurIrmUHZqHutkWos=,tag:BGwFQHx321pi4EdGXF6YlA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
