smtp_username: ENC[AES256_GCM,data:o2mH8UvgHs7p8TrtLbmlR0j/Z3I=,iv:7/Hghf8oKMY/2dOdoi/SeGCGzBSpJV7dWp2Q2+Gi/vE=,tag:ou3nK2VeHxDFFHiYnO5uYw==,type:str]
smtp_password: ENC[AES256_GCM,data:j77Tx9GLIwLJAD7WoK16V9xBnXz88uXmh9cPH6d/3+Q=,iv:10IttZ4KprxBRHxXluCR4+5fHPqTkuUsDWztUOipYdc=,tag:T2xqr7GsViS0ZlSUsnlGDQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMjcrVFVzQ2ZrcVZXRXg1
            REpTcmFaTVpkWTFGWjJnbHlxbElGUWVwdFRJCkdJRlZCQzdtNmFENDdXOW01UzNh
            cnNHZzZ0RHUvWG5Ja3I4dTRUNHJwUGcKLS0tIERNdHY5Z1FybkFCaFdwbXpPRmJq
            UG4raXFLMWhXOCtrVGVBdEZTM0NQWFUKACGZ07ONETRp45WO6xCpbqsaGkNIiKSR
            brucdiuDz3ek5EhvAc0Q379YNAwpvCb8rkug/wxy90SFhNcygPYCQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejlnhgwfnj7p5gxhvp8w0w52fg5n9k57xxzja2xqyneyu42ludyse4lfa6
    lastmodified: "2026-08-25T10:09:23Z"
    mac: ENC[AES256_GCM,data:Ua3P3URvorWtd2xi/gHrMi0gVRAKww/e4ujJF0dV6C94o5Diu/YdFKNZw7jZ/+x6BXgD7qf6iYnIbIXUmlhah5S2qbLPP+sd2+jVXBK0CIUjiyfqRtGvb5i+DWRqwiNi5MRIIGRdqCJpD28BYG1JauO1gF95iOuVXNTmLwJbJkY=,iv:1PNDKp+vrm/slLFKjDEuoASCCZBLQ7b3VrF7GYWxTJk=,tag:v/OwjJ3gJOpi1FE1s9NLzg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
