apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pella
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tobiasmeier-84/gitops-homelab.git
    targetRevision: master
    path: gitops/manifests/pella
  destination:
    server: https://kubernetes.default.svc
    namespace: pella
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true