---
- name: Add kubectl PATH and KUBECONFIG to shell profile
  blockinfile:
    path: /home/{{ ansible_user }}/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK - rke2-kubectl-env"
    block: |
      export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
      export PATH=$PATH:/var/lib/rancher/rke2/bin