apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guanshiyin
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://collaboraonline.github.io/online/
      chart: collabora-online
      targetRevision: "*"
      helm:
        values: |
          replicaCount: 1
          collabora:
            aliasgroups:
              - host: "https://guanshiyin.app.solsys.dev:443"
                aliases:
                  - "https://office.app.solsys.dev:443"
            extra_params: "--o:ssl.enable=false --o:ssl.termination=true --o:num_prespawn_children=4"
            server_name: "guanshiyin.app.solsys.dev:443"
          ingress:
            enabled: false
          autoscaling:
            enabled: false
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "2Gi"
    - repoURL: https://github.com/tobiasmeier-84/gitops-homelab.git
      targetRevision: master
      path: gitops/manifests/guanshiyin
  destination:
    server: https://kubernetes.default.svc
    namespace: rocinante
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
