apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: barbapiccola
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tobiasmeier-84/gitops-homelab.git
    targetRevision: master
    path: gitops/manifests/barbapiccola
  destination:
    server: https://kubernetes.default.svc
    namespace: rocinante
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: postgresql.cnpg.io
      kind: Cluster
      jsonPointers:
        - /spec/affinity
        - /spec/enablePDB
        - /spec/enableSuperuserAccess
        - /spec/failoverDelay
        - /spec/imageName
        - /spec/logLevel
        - /spec/maxSyncReplicas
        - /spec/minSyncReplicas
        - /spec/monitoring
        - /spec/postgresGID
        - /spec/postgresUID
        - /spec/postgresql
        - /spec/primaryUpdateMethod
        - /spec/primaryUpdateStrategy
        - /spec/probes
        - /spec/replicationSlots
        - /spec/resources
        - /spec/smartShutdownTimeout
        - /spec/startDelay
        - /spec/stopDelay
        - /spec/switchoverDelay
        - /spec/bootstrap/initdb/encoding
        - /spec/bootstrap/initdb/localeCType
        - /spec/bootstrap/initdb/localeCollate