apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guanshiyin
  namespace: rocinante
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
    - hosts:
        - guanshiyin.app.solsys.dev
        - office.app.solsys.dev
      secretName: guanshiyin-tls
  rules:
    - host: guanshiyin.app.solsys.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: guanshiyin-collabora-online
                port:
                  number: 9980
    - host: office.app.solsys.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: guanshiyin-collabora-online
                port:
                  number: 9980
