apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-bulk-single-replica
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  numberOfReplicas: "1"
  diskSelector: "bulk"