apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-bulk-single-replica
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
      - key: kubernetes.io/hostname
        values:
          - rhea
parameters:
  numberOfReplicas: "1"
  diskSelector: "bulk"
  strictTopology: "true"
